### ISSUE TITLE
[Question] 2.0.5 升级到2.3.0 启动时无法连接server, 报 Server disconnected. Retry in 10s...

### ISSUE THREAD

**Issue by mocobk** [SonicCloudOrg/sonic-agent#306]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.3.0

### Deploy platform

macosx-x86_64

### Minimal reproduce step

启动后会出现连接不上，一直报下面日志，切换到 2.0.5则正常
2023-02-10 17:26:13.561 - INFO 69221 --- [WebSocketConnectReadThread-64] o.c.s.agent.transport.TransportClient    : Server disconnected. Retry in 10s...
![image](https://user-images.githubusercontent.com/26194964/218062658-da30008e-20a6-42c0-9a96-04328a16e486.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
请问是怎么升级的呢？pom中的releaseMode是什么？后面更改的文件有同步吗？yml文件也请展示下

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-agent/blob/main/src/main/java/org/cloud/sonic/agent/transport/TransportConnectionThread.java 你这个文件是不是自己改动过？可以附上这个文件截图和yml截图，另外请问server是本地部署吗？

**Comment by mocobk** [comment]
文件没有改动，我是这样操作的

1. 容器部署最新的 2.3.0 server 端
2. pull agent 代码并check 到 tag 2.3.0
3. 配置 yml 文件
4. 启动agent
然后就一直报上面的连接问题，如果把 agent 代码切换到 2.0.5 则能正常连接，从release 包下载的 2.3.0 agent 也可以

TransportConnectionThread.java
```java
package org.cloud.sonic.agent.transport;

import com.alibaba.fastjson.JSONObject;
import lombok.extern.slf4j.Slf4j;
import org.cloud.sonic.agent.tools.SpringTool;

import java.net.URI;
import java.util.concurrent.TimeUnit;

/**
 * @author Eason
 * @date 2022/6/12 02:45
 */
@Slf4j
public class TransportConnectionThread implements Runnable {
    /**
     * second
     */
    public static final long DELAY = 10;

    public static final String THREAD_NAME = "transport-connection-thread";

    public static final TimeUnit TIME_UNIT = TimeUnit.SECONDS;

    String serverHost = String.valueOf(SpringTool.getPropertiesValue("sonic.server.host"));
    Integer serverPort = Integer.valueOf(SpringTool.getPropertiesValue("sonic.server.port"));
    String key = String.valueOf(SpringTool.getPropertiesValue("sonic.agent.key"));

    boolean isRelease = Boolean.valueOf(SpringTool.getPropertiesValue("sonic.release-mode"));

    @Override
    public void run() {
        Thread.currentThread().setName(THREAD_NAME);
        if (TransportWorker.client == null) {
            if (!TransportWorker.isKeyAuth) {
                return;
            }
            String url = String.format("ws://%s:%d%s/websockets/agent/%s",
                    serverHost, serverPort, isRelease ? "/server" : "", key).replace(":80/", "/");
            URI uri = URI.create(url);
            TransportClient transportClient = new TransportClient(uri);
            transportClient.connect();
        } else {
            JSONObject ping = new JSONObject();
            ping.put("msg", "ping");
            TransportWorker.send(ping);
        }
    }
}
```
application-sonic-agent.yml
```yml
sonic:
  agent:
    # Replace with ipv4 of the agent machine | 替换为部署Agent机器的ipv4
    host: 10.91.xx.xx
    # Replace with the port of the agent service, which can be changed by yourself | 替换为Agent服务的端口，可以自行更改
    port: 7777
    # Replace with the key of agent generated by the new front-end | 替换为前端新增Agent生成的key
    key: 02aa2ca9-xxxx-abc808f178b5
  server:
    # Change to SONIC_SERVER_HOST of server | 改成server的SONIC_SERVER_HOST
    host: 9.134.xx.xx
    # Change to SONIC_SERVER_PORT of server | 改成server的SONIC_SERVER_PORT
    port: 3000

modules:
  android:
    # Whether to enable Android module | 是否开启安卓模块
    enable: true
    # Whether to enable sonic-android-supply module | 是否开启sonic-android-supply功能
    use-sas: true
  ios:
    # Whether to turn on the iOS module. Please ensure that iTunes is installed on this computer for Windows users | 是否开启iOS模块。开启的windows用户请确保本机已安装iTunes
    enable: true
    # Replace with the bundleId of wda. If there is no. xcrunner suffix, it will be automatically completed. | 替换为wda的bundleId，如果没有.xctrunner后缀会自动补全
    wda-bundle-id: com.sonic.WebDriverAgentRunner
  sgm:
    # Whether to enable the sonic-go-mitmproxy module | 是否开启sonic-go-mitmproxy功能
    enable: true
```
